dda-user-cratedist: trusty
language: clojure

services:
  - docker

stages:
  - build

env:
  global:
    - DOCKER_USERNAME: domaindrivenarchitecture
    - secure:
jobs:
  include:
    - stage: build
      script:
        - # build
        - lein test
        - lein uberjar
        - md5sum target/dda-user-crate-standalone.jar > target/dda-user-crate-standalone.jar.md5
        - # create docker image
        - docker build -t dda-user-crate --file integration/docker/image/Dockerfile .
        - # integration test on docker image level
        - docker build -t dda-user-crate-test --file integration/docker/test/Dockerfile .
      deploy:
        skip_cleanup: true
        provider: releases
        overwrite: true
        draft: true
        api_key:
          secure:
        file:
          - target/dda-user-crate-standalone.jar
          - target/dda-user-crate-standalone.jar.md5
        provider: script
        script: bash integration/docker/publish.sh dda-user-crate
