dda-user-cratedist: trusty
language: clojure

before_install:
  - sudo apt-get -y install python3-pip
  - pip3 install pybuilder ddadevops deprecation
  - pip3 install python_terraform
addons:
  apt:
    update: true

services:
  - docker

stages:
  - build

jobs:
  include:
    - stage: build
      script:
        - # build
        - lein test
        - lein uberjar
        - md5sum target/uberjar/dda-user-standalone.jar > target/uberjar/dda-user-standalone.jar.md5
        - sha256sum target/uberjar/dda-user-standalone.jar > target/uberjar/dda-user-standalone.jar.sha256
        - sha512sum target/uberjar/dda-user-standalone.jar > target/uberjar/dda-user-standalone.jar.sha512
        - # integration test as root
        - cd integration/docker-as-root && pyb image test
      deploy:
        - provider: releases
          skip_cleanup: true
          on:
            tags: true
          api_key:
            secure: "ppcNpCqLBWzTDLuPZia1Toz/BuBHtNthlWvQ7EBd6kOGby8TmFuqeOf4TOUYVX7DDOtOdJ9RKZtwhqLvhhNzmN0UjRY1mgyFQvVytZfSNhiX/2//ldAt05Mu3ozi8jm1lnLTj8pEL354ZhemgYEFhzm8dvLCLo+a83knUaGU2FURd5VV4IKMxqpSLc9mz9BbEXUWncQcy9LDZF/CBiiZKUAhcIwBfa7hGh3uDcvHiBNL+F/RZGjyQyaH/qmOFFAPkZFBYpJHGbT767ejjl6oxabKeccznxqSSevAAZasTa8PKg4lXvm0+RvUekKgObyueU+t4Fc/Md+n8yHwlgjRgyQ0oAeEMsERSsVjuqT0itkoiTYLZtRZ3PGjVl+izit9yW6l+Er1I7xfOwY0WCVkkpQFMhICruZgvD8krkd8Z4dXQj2NilZCptD6jcv/CQxBmEjNZWcftxf1wai5qon5KiR3cLSFq5lx7DNApkuCp2rgSFWNAsznmdRnW8xk975aFpUULHEWlESLu2dZt9MRyIQsISqAhrTrSu+mtulOfNlt5kG2USMWwRs6pbVuXF5R8+G8sJWZEgF1ESg1W1TgVb2YD/ejWCI9p+EgCh9U2ql6JZr3g0cZdWKv3HJGSThHXfoE/40qgeyAhbROaNATXRIbnQJcFocsZ34PlGEkBcs="
          file:
            - target/uberjar/dda-user-standalone.jar
            - target/uberjar/dda-user-standalone.jar.md5
            - target/uberjar/dda-user-standalone.jar.sha256
            - target/uberjar/dda-user-standalone.jar.sha512